---
# Security hardening tasks

- name: Install security packages
  apt:
    name:
      - ufw
      - fail2ban
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Configure UFW firewall
  block:
    - name: Reset UFW to defaults
      ufw:
        state: reset
      when: firewall_enabled | default(true)

    - name: Set UFW default policies
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }
      when: firewall_enabled | default(true)

    - name: Allow SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp
      when: firewall_enabled | default(true)

    - name: Allow HTTP and HTTPS
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ firewall_allowed_tcp_ports }}"
      when: firewall_enabled | default(true)

    - name: Enable UFW
      ufw:
        state: enabled
      when: firewall_enabled | default(true)

- name: Configure Fail2Ban
  block:
    - name: Create Fail2Ban jail configuration
      template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
        backup: true
      notify: restart fail2ban

    - name: Ensure Fail2Ban is running and enabled
      service:
        name: fail2ban
        state: started
        enabled: true
      when: security.fail2ban_enabled | default(true)

- name: Configure automatic updates
  block:
    - name: Configure unattended upgrades
      template:
        src: 50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        backup: true
      when: security.automatic_updates | default(true)

    - name: Enable automatic updates
      template:
        src: 20auto-upgrades.j2
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        backup: true
      when: security.automatic_updates | default(true)

- name: Secure shared memory
  mount:
    path: /run/shm
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noexec,nosuid
    state: mounted

- name: Set secure permissions on sensitive files
  file:
    path: "{{ item }}"
    mode: '0600'
  loop:
    - /etc/shadow
    - /etc/gshadow
  ignore_errors: true

- name: Disable unused network protocols
  lineinfile:
    path: /etc/modprobe.d/blacklist-rare-network.conf
    line: "{{ item }}"
    create: true
  loop:
    - "install dccp /bin/true"
    - "install sctp /bin/true"
    - "install rds /bin/true"
    - "install tipc /bin/true"
