---
# PHP installation and configuration

- name: Add PHP repository
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
    update_cache: true

- name: Install PHP and modules
  apt:
    name:
      - "php{{ php.version }}"
      - "libapache2-mod-php{{ php.version }}"
    state: present
  notify: restart apache

- name: Install PHP modules
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ php.modules }}"
  notify: restart apache

- name: Configure PHP for Apache
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php.version }}/apache2/php.ini"
    backup: true
  notify: restart apache

- name: Configure PHP CLI
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php.version }}/cli/php.ini"
    backup: true

- name: Install Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: '0755'

- name: Run Composer installer
  command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Make Composer executable
  file:
    path: /usr/local/bin/composer
    mode: '0755'

- name: Create PHP session directory
  file:
    path: /var/lib/php/sessions
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create PHP upload directory
  file:
    path: /var/www/uploads
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Set PHP-FPM configuration (if using FPM)
  template:
    src: www.conf.j2
    dest: "/etc/php/{{ php.version }}/fpm/pool.d/www.conf"
    backup: true
  when: "'php-fpm' in php.modules"
  notify: restart php-fpm

- name: Ensure PHP-FPM is running (if installed)
  service:
    name: "php{{ php.version }}-fpm"
    state: started
    enabled: true
  when: "'php-fpm' in php.modules"
